#!/bin/bash
# Assume ssh login to remote host, and installs personal config via git.

if [ "$1" = "-h" ]; then
  echo "$0" HOME GIT
  exit 0
fi

HOST=${1:?need to specify the SSH login to configure}
HOMEGIT=$2
HOMEGIT=${HOMEGIT:="https://github.com/hayeah/homegit.git"}

ssh $HOST <<-HERE
echo $HOMEGIT
test ! -d  ~/homegit && git clone $HOMEGIT ~/homegit
cd ~/homegit && git pull -f && ./deploy
HERE